## Loading data

In [20]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

irisdf = px.data.iris()
irisdf.head(5)

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

## Preprocessing data

In [2]:
irisdf.shape

(150, 6)

In [3]:
irisdf.dtypes.to_frame()

                    0
sepal_length  float64
sepal_width   float64
petal_length  float64
petal_width   float64
species        object
species_id      int64

In [4]:
irisdf.isnull().sum().to_frame()

              0
sepal_length  0
sepal_width   0
petal_length  0
petal_width   0
species       0
species_id    0

In [21]:
irisdf[irisdf.duplicated()]

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
34,4.9,3.1,1.5,0.1,setosa,1
37,4.9,3.1,1.5,0.1,setosa,1
142,5.8,2.7,5.1,1.9,virginica,3

In [5]:
duplicates = irisdf[irisdf.duplicated()]
print("Number of duplicates:", len(duplicates))

Number of duplicates: 3

In [6]:
irisdf = irisdf.drop_duplicates()

In [7]:
irisdf.describe()

       sepal_length  sepal_width  petal_length  petal_width  species_id
count    147.000000   147.000000    147.000000   147.000000  147.000000
mean       5.856463     3.055782      3.780272     1.208844    2.006803
std        0.829100     0.437009      1.759111     0.757874    0.815069
min        4.300000     2.000000      1.000000     0.100000    1.000000
25%        5.100000     2.800000      1.600000     0.300000    1.000000
50%        5.800000     3.000000      4.400000     1.300000    2.000000
75%        6.400000     3.300000      5.100000     1.800000    3.000000
max        7.900000     4.400000      6.900000     2.500000    3.000000

In [8]:
species=irisdf["species"].unique()
print(species)

['setosa' 'versicolor' 'virginica']

## Data visualization

## Scatter plot

In [9]:
fig = px.scatter(
    irisdf,
    x="petal_length",
    y="petal_width",
    color="species",
    facet_col='species',
    hover_data={
        'species': False,
        'sepal_length': ':.2f',
        'petal_width': True,
        'sepal_width': ':.2f',
    }
)
fig.show()
fig.write_html("subplot.html")

In [10]:
fig = px.scatter(
    irisdf,
    x="petal_length",
    y="petal_width",
    color="species",
    hover_data={
        'species': False,
        'sepal_length': ':.2f',
        'petal_width': True,
        'sepal_width': ':.2f',
    }
)

cluster0 = [dict(type="circle",
                 xref="x", yref="y",
                 x0=min(irisdf[irisdf['species'] == "setosa"]["petal_length"]),
                 y0=min(irisdf[irisdf['species'] == "setosa"]["petal_width"]),
                 x1=max(irisdf[irisdf['species'] == "setosa"]["petal_length"]),
                 y1=max(irisdf[irisdf['species'] == "setosa"]["petal_width"]),
                 line=dict(color="Blue"))]

cluster1 = [dict(type="circle",
                 xref="x", yref="y",
                 x0=min(irisdf[irisdf['species'] == "versicolor"]["petal_length"]),
                 y0=min(irisdf[irisdf['species'] == "versicolor"]["petal_width"]),
                 x1=max(irisdf[irisdf['species'] == "versicolor"]["petal_length"]),
                 y1=max(irisdf[irisdf['species'] == "versicolor"]["petal_width"]),
                 line=dict(color="Red"))]

cluster2 = [dict(type="circle",
                 xref="x", yref="y",
                 x0=min(irisdf[irisdf['species'] == "virginica"]["petal_length"]),
                 y0=min(irisdf[irisdf['species'] == "virginica"]["petal_width"]),
                 x1=max(irisdf[irisdf['species'] == "virginica"]["petal_length"]),
                 y1=max(irisdf[irisdf['species'] == "virginica"]["petal_width"]),
                 line=dict(color="Green"))]

fig.update_layout(
    updatemenus=[
        dict(buttons=list([
            dict(label="None",
                 method="relayout",
                 args=["shapes", []]),
            dict(label="Cluster 0 (Setosa)",
                 method="relayout",
                 args=["shapes", cluster0]),
            dict(label="Cluster 1 (Versicolor)",
                 method="relayout",
                 args=["shapes", cluster1]),
            dict(label="Cluster 2 (Virginica)",
                 method="relayout",
                 args=["shapes", cluster2]),
            dict(label="All Clusters",
                 method="relayout",
                 args=["shapes", cluster0 + cluster1 + cluster2])
        ]),
        )
    ]
)

fig.show()
fig.write_html("clustered.html")

In [23]:
fig = px.scatter(
    irisdf,
    x="petal_length",
    y="petal_width",
)

fig.update_layout(
    updatemenus=[
        dict(
            buttons=list([
                dict(label="Petal Dimensions",
                     method="update",
                     args=[{"x": [irisdf["petal_length"]],
                            "y": [irisdf["petal_width"]]},
                           {"xaxis": {"title": "Petal Length"},
                            "yaxis": {"title": "Petal Width"}}]),
                dict(label="Sepal Dimensions",
                     method="update",
                     args=[{"x": [irisdf["sepal_length"]],
                            "y": [irisdf["sepal_width"]]},
                           {"xaxis": {"title": "Sepal Length"},
                            "yaxis": {"title": "Sepal Width"}}])
            ]),

        )
    ],
    title="Iris Dataset: Toggle Between Petal and Sepal Dimensions",
    xaxis_title="Petal Length",
    yaxis_title="Petal Width"
)
fig.show()
fig.write_html("dropdown.html")

In [12]:
fig = px.scatter(
    irisdf,
    x="petal_length",
    y="petal_width",
    animation_frame="species", 
    animation_group="petal_length"
)

fig.show()

## Bar plot

In [13]:
fig = make_subplots(rows=1, cols=len(species), subplot_titles=species)

for i, sp in enumerate(species, start=1):
    species_data = irisdf[irisdf['species'] == sp]
    count = species_data.shape[0]

    fig.add_trace(
        go.Bar(x=[sp], y=[count], name=sp),
        row=1, col=i
    )

fig.update_layout(
    title_text='Count of Different Species',  
    xaxis_title='Species',
    yaxis_title='Count',
)
fig.show()

fig.write_html("barplot.html")

## Box plot

In [14]:
fig = px.box(irisdf, x="species", y="sepal_length")
fig.show()
fig.write_html("boxplot.html")

## Heatmap

In [15]:
heatmap_df = irisdf.drop(['species', 'species_id'], axis=1)
heatmap_df.corr()

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.109321      0.871305     0.817058
sepal_width      -0.109321     1.000000     -0.421057    -0.356376
petal_length      0.871305    -0.421057      1.000000     0.961883
petal_width       0.817058    -0.356376      0.961883     1.000000

In [16]:
fig = px.imshow(heatmap_df.corr())
fig.show()
fig.write_html("heatmap.html")

## Histogram of petal lenght

In [17]:
fig = px.histogram(irisdf, x="petal_length")
fig.show()
fig.write_html("histogramplot.html")

## Normalization

In [18]:
import scipy
data_norm_to_0_1 = [
    number/scipy.linalg.norm(irisdf["petal_length"]) for number in irisdf["petal_length"]]
fig = px.histogram(data_norm_to_0_1)
fig.show()
fig.write_html("normalhistogramplot.html")